In [1]:
import pandas as pd

In [2]:
departement_code= ['16','17','19','23','24','33','40','47','64','79','86','87']

In [3]:
df = pd.read_excel("depense-recette.xlsx")
df=df.transpose()
df.columns = df.iloc[0]
df = df.drop(df.index[0])
df["Année"] = df.index
df=df.reset_index(drop=True)
df= df.append(df[df["Année"].eq(2023)]).sort_values("Année").reset_index(drop=True)
df.iloc[46,3] =2024
#df.reindex(df.index.append(df.index[df["Année"]=="2023"])).sort_index()
df

/var/folders/6l/7z68vf196xjd9mbcdm1sw6pm0000gn/T/ipykernel_57659/4107178453.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df= df.append(df[df["Année"].eq(2023)]).sort_values("Année").reset_index(drop=True)

Dépense et recette   Dépenses   Recettes Déficit au sens de Maastricht Année
0                   46.318193  44.521342                          -1.8  1978
1                    46.61834  46.136484                          -0.5  1979
2                    47.58252  47.153917                          -0.4  1980
3                   50.138131  47.731023                          -2.4  1981
4                   51.440216  48.603591                          -2.8  1982
5                    51.96668  49.425791                          -2.5  1983
6                   53.001105  50.265137                          -2.7  1984
7                   53.603595  50.631255                          -3.0  1985
8                    52.94964  49.752337                          -3.2  1986
9                   52.352267  50.337776                          -2.0  1987
10                  51.621774  49.057387                          -2.6  1988
11                  50.460486  48.678445                          -1.8  1989
12                  51.143747  48.709633                          -2.4  1990
13                  52.294044  49.431193                          -2.9  1991
14                  53.553916  48.952699                          -4.6  1992
15                   56.17868  49.820049                          -6.4  1993
16                   55.55163   50.12857                          -5.4  1994
17                   55.84714   50.75479                          -5.1  1995
18                  55.780783  51.901094                          -3.9  1996
19                  55.434677  51.732159                          -3.7  1997
20                  53.755334  51.373885                          -2.4  1998
21                  53.432503  51.894723                          -1.5  1999
22                  52.438558  51.130402                          -1.3  2000
23                    52.5436  51.133731                          -1.4  2001
24                  53.601956  50.445388                          -3.2  2002
25                  54.075188  50.008322                          -4.1  2003
26                  53.749792   50.21111                          -3.5  2004
27                   54.14462  50.644919                          -3.5  2005
28                  53.688306   51.03362                          -2.7  2006
29                  53.533991  50.549707                          -3.0  2007
30                  54.217594  50.719762                          -3.5  2008
31                  57.973263  50.597088                          -7.4  2009
32                  57.719047  50.564169                          -7.2  2010
33                  57.098837  51.784653                          -5.3  2011
34                  57.877755  52.707946                          -5.2  2012
35                  58.679574  53.733781                          -4.9  2013
36                  58.487751  53.905669                          -4.6  2014
37                  57.677827  53.780458                          -3.9  2015
38                  57.322035  53.561052                          -3.8  2016
39                  57.523091  54.168734                          -3.4  2017
40                       56.2       53.9                          -2.3  2018
41                       55.2       52.8                          -2.4  2019
42                       61.7       52.8                          -8.9  2020
43                       59.6       53.0                          -6.6  2021
44                       58.8       54.0                          -4.8  2022
45                       57.3       51.9                          -5.5  2023
46                       57.3       51.9                          -5.5  2024

In [4]:
df_passing_dep = []
for dep in departement_code :
    df_dep = df.copy()
    df_dep["Code du département"] = dep
    df_passing_dep.append(df_dep)
len(df_passing_dep)

12

In [5]:
df_concat =  pd.concat(df_passing_dep)
df_concat

Dépense et recette,Dépenses,Recettes,Déficit au sens de Maastricht,Année,Code du département
0,46.318193,44.521342,-1.8,1978,16
1,46.61834,46.136484,-0.5,1979,16
2,47.58252,47.153917,-0.4,1980,16
3,50.138131,47.731023,-2.4,1981,16
4,51.440216,48.603591,-2.8,1982,16
...,...,...,...,...,...
42,61.7,52.8,-8.9,2020,87
43,59.6,53.0,-6.6,2021,87
44,58.8,54.0,-4.8,2022,87
45,57.3,51.9,-5.5,2023,87
46,57.3,51.9,-5.5,2024,87

In [6]:
df_concat.to_csv("depense-recette.csv")