In [69]:
import pandas as pd

In [70]:
# Lecture des fichiers csv
df_sir_com_2001 = pd.read_csv("ircom-communes-revenus-2001.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2002 = pd.read_csv("ircom-communes-revenus-2002.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2003 = pd.read_csv("ircom_communes_complet_revenus_2003.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2004 = pd.read_csv("ircom_communes_complet_revenus_2004.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2005 = pd.read_csv("ircom_communes_complet_revenus_2005.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2006 = pd.read_csv("ircom_communes_complet_revenus_2006.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2008 = pd.read_csv("ircom_communes_complet_revenus_2008.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2009 = pd.read_csv("ircom_communes_complet_revenus_2009.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2011 = pd.read_csv("ircom_communes_complet_revenus_2011.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2012 = pd.read_csv("ircom_communes_complet_revenus_2012.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2013 = pd.read_csv("ircom_communes_complet_revenus_2013.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2014 = pd.read_csv("ircom_communes_complet_revenus_2014.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2015 = pd.read_csv("ircom_communes_complet_revenus_2015.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2016 = pd.read_csv("ircom_communes_complet_revenus_2016.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2017 = pd.read_csv("ircom_communes_complet_revenus_2017.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2019 = pd.read_csv("ircom_communes_complet_revenus_2019.csv", sep=",", encoding = "ISO-8859-1")
df_sir_com_2020 = pd.read_csv("ircom_communes_complet_revenus_2020.csv", sep=",", encoding = "ISO-8859-1")

In [71]:
def process(df: pd.core.frame.DataFrame, year: int):
    df.info()
    
    # Supression des colonnes inutiles
    
    df = df.drop('@odata.etag', axis=1)
    df = df.drop('ItemInternalId', axis=1)
    df = df.drop('Commune', axis = 1)
    
    # Ajout de l'ann√©e
    df['Annee'] = year
    
    # Suppression des valeurs n.c.
    
    for col in df.columns:
        df.drop(df[df[col]  == 'n.c.'].index, inplace = True)
        df.drop(df[df[col]  == '. '].index, inplace = True)
        df.drop(df[df[col]  == '#VALUE!'].index, inplace = True)
        

    
    # Convertion des types de colonne
    
    for col in ['Libelle_de_la_commune', 'Revenu_fiscal_de_reference_par_tranche']:
        df[col] = df[col].astype(str)
    
    for col in ['Nombre_de_foyers_fiscaux', 'Nombre_de_foyers_fiscaux_imposes', 'Traitements_et_salaires_Nombre_de_foyers_concernes', 'Retraites_et_pensions_Nombre_de_foyers_concernes']:
        df[col] = df[col].astype(int)
    
    for col in ['Revenu_fiscal_de_reference_des_foyers_fiscaux', 'Impot_net_total', 'Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes', 'Traitements_et_salaires_Montant', 'Retraites_et_pensions_Montant']:
        df[col] = df[col].astype(float)

    df.to_csv('df_sir_com_' + str(year) + '.csv')

In [72]:
df_sir_com_2001 = process(df_sir_com_2001, 2001)
df_sir_com_2002 = process(df_sir_com_2002, 2002)
df_sir_com_2003 = process(df_sir_com_2003, 2003)
df_sir_com_2004 = process(df_sir_com_2004, 2004)
df_sir_com_2005 = process(df_sir_com_2005, 2005)
df_sir_com_2006 = process(df_sir_com_2006, 2006)
df_sir_com_2008 = process(df_sir_com_2008, 2008)
df_sir_com_2009 = process(df_sir_com_2009, 2009)
df_sir_com_2011 = process(df_sir_com_2011, 2011)
df_sir_com_2012 = process(df_sir_com_2012, 2012)
df_sir_com_2013 = process(df_sir_com_2013, 2013)
df_sir_com_2014 = process(df_sir_com_2014, 2014)
df_sir_com_2015 = process(df_sir_com_2015, 2015)
df_sir_com_2016 = process(df_sir_com_2016, 2016)
df_sir_com_2017 = process(df_sir_com_2017, 2017)
df_sir_com_2019 = process(df_sir_com_2019, 2019)
df_sir_com_2020 = process(df_sir_com_2020, 2020)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36715 entries, 0 to 36714
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36715 non-null  object
 2   Dep                                                    36715 non-null  object
 3   Commune                                                36715 non-null  int64
 4   Libelle_de_la_commune                                  36715 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36715 non-null  object
 6   Nombre_de_foyers_fiscaux                               36715 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36715 non-null  object
 8   Impot_net_total                                        36715 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36715 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36715 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36715 non-null  object
 12  Traitements_et_salaires_Montant                        36715 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36715 non-null  object
 14  Retraites_et_pensions_Montant                          36715 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36714 entries, 0 to 36713
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36714 non-null  object
 2   Dep                                                    36714 non-null  object
 3   Commune                                                36714 non-null  int64
 4   Libelle_de_la_commune                                  36714 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36714 non-null  object
 6   Nombre_de_foyers_fiscaux                               36714 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36714 non-null  object
 8   Impot_net_total                                        36714 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36714 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36714 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36714 non-null  object
 12  Traitements_et_salaires_Montant                        36714 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36714 non-null  object
 14  Retraites_et_pensions_Montant                          36714 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36176 entries, 0 to 36175
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36176 non-null  object
 2   Dep                                                    36176 non-null  object
 3   Commune                                                36176 non-null  int64
 4   Libelle_de_la_commune                                  36176 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36176 non-null  object
 6   Nombre_de_foyers_fiscaux                               36176 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36176 non-null  object
 8   Impot_net_total                                        36176 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36176 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36176 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36176 non-null  object
 12  Traitements_et_salaires_Montant                        36176 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36176 non-null  object
 14  Retraites_et_pensions_Montant                          36176 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36167 entries, 0 to 36166
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36167 non-null  object
 2   Dep                                                    36167 non-null  object
 3   Commune                                                36167 non-null  int64
 4   Libelle_de_la_commune                                  36167 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36167 non-null  object
 6   Nombre_de_foyers_fiscaux                               36167 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36167 non-null  object
 8   Impot_net_total                                        36167 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36167 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36167 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36167 non-null  object
 12  Traitements_et_salaires_Montant                        36167 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36167 non-null  object
 14  Retraites_et_pensions_Montant                          36167 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35260 entries, 0 to 35259
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         35260 non-null  object
 2   Dep                                                    35260 non-null  int64
 3   Commune                                                35260 non-null  int64
 4   Libelle_de_la_commune                                  35260 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 35260 non-null  object
 6   Nombre_de_foyers_fiscaux                               35260 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          35260 non-null  object
 8   Impot_net_total                                        35260 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       35260 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  35260 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     35260 non-null  object
 12  Traitements_et_salaires_Montant                        35260 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       35260 non-null  object
 14  Retraites_et_pensions_Montant                          35260 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 4.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35803 entries, 0 to 35802
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         35803 non-null  object
 2   Dep                                                    35803 non-null  int64
 3   Commune                                                35803 non-null  int64
 4   Libelle_de_la_commune                                  35803 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 35803 non-null  object
 6   Nombre_de_foyers_fiscaux                               35803 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          35803 non-null  object
 8   Impot_net_total                                        35803 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       35803 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  35803 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     35803 non-null  object
 12  Traitements_et_salaires_Montant                        35803 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       35803 non-null  object
 14  Retraites_et_pensions_Montant                          35803 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 4.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35800 entries, 0 to 35799
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         35800 non-null  object
 2   Dep                                                    35800 non-null  int64
 3   Commune                                                35800 non-null  int64
 4   Libelle_de_la_commune                                  35800 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 35800 non-null  object
 6   Nombre_de_foyers_fiscaux                               35800 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          35800 non-null  object
 8   Impot_net_total                                        35800 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       35800 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  35800 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     35800 non-null  object
 12  Traitements_et_salaires_Montant                        35800 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       35800 non-null  object
 14  Retraites_et_pensions_Montant                          35800 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 4.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35747 entries, 0 to 35746
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         35747 non-null  object
 2   Dep                                                    35747 non-null  int64
 3   Commune                                                35747 non-null  int64
 4   Libelle_de_la_commune                                  35747 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 35747 non-null  object
 6   Nombre_de_foyers_fiscaux                               35747 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          35747 non-null  object
 8   Impot_net_total                                        35747 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       35747 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  35747 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     35747 non-null  object
 12  Traitements_et_salaires_Montant                        35747 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       35747 non-null  object
 14  Retraites_et_pensions_Montant                          35747 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 4.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36704 entries, 0 to 36703
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36704 non-null  object
 2   Dep                                                    36704 non-null  object
 3   Commune                                                36704 non-null  int64
 4   Libelle_de_la_commune                                  36704 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36704 non-null  object
 6   Nombre_de_foyers_fiscaux                               36704 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36704 non-null  object
 8   Impot_net_total                                        36704 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36704 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36704 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36704 non-null  object
 12  Traitements_et_salaires_Montant                        36704 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36704 non-null  object
 14  Retraites_et_pensions_Montant                          36704 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36304 entries, 0 to 36303
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36304 non-null  object
 2   Dep                                                    36304 non-null  object
 3   Commune                                                36304 non-null  int64
 4   Libelle_de_la_commune                                  36304 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36304 non-null  object
 6   Nombre_de_foyers_fiscaux                               36304 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36304 non-null  object
 8   Impot_net_total                                        36304 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36304 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36304 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36304 non-null  object
 12  Traitements_et_salaires_Montant                        36304 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36304 non-null  object
 14  Retraites_et_pensions_Montant                          36304 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36697 entries, 0 to 36696
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36697 non-null  object
 2   Dep                                                    36697 non-null  object
 3   Commune                                                36697 non-null  int64
 4   Libelle_de_la_commune                                  36697 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36697 non-null  object
 6   Nombre_de_foyers_fiscaux                               36697 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36697 non-null  object
 8   Impot_net_total                                        36697 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36697 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36697 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36697 non-null  object
 12  Traitements_et_salaires_Montant                        36697 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36697 non-null  object
 14  Retraites_et_pensions_Montant                          36697 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36690 entries, 0 to 36689
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36690 non-null  object
 2   Dep                                                    36690 non-null  object
 3   Commune                                                36690 non-null  int64
 4   Libelle_de_la_commune                                  36690 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36690 non-null  object
 6   Nombre_de_foyers_fiscaux                               36690 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36690 non-null  object
 8   Impot_net_total                                        36690 non-null  object
 9   Nombre_de_foyers_fiscaux_imposes                       36690 non-null  object
 10  Revenu_fiscal_de_reference_des_foyers_fiscaux_imposes  36690 non-null  object
 11  Traitements_et_salaires_Nombre_de_foyers_concernes     36690 non-null  object
 12  Traitements_et_salaires_Montant                        36690 non-null  object
 13  Retraites_et_pensions_Nombre_de_foyers_concernes       36690 non-null  object
 14  Retraites_et_pensions_Montant                          36690 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36813 entries, 0 to 36812
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   @odata.etag                                            0 non-null      float64
 1   ItemInternalId                                         36813 non-null  object
 2   Dep                                                    36813 non-null  object
 3   Commune                                                36813 non-null  int64
 4   Libelle_de_la_commune                                  36813 non-null  object
 5   Revenu_fiscal_de_reference_par_tranche                 36813 non-null  object
 6   Nombre_de_foyers_fiscaux                               36813 non-null  object
 7   Revenu_fiscal_de_reference_des_foyers_fiscaux          36813 non-null  object
 8   Impot_net_total                                        36813 non-null  object