In [1]:
import pandas as pd
import functools

In [2]:
dicT_dep ={
    "Charente-Maritime": "17",
    "Charente": "16",

"Corrèze" :"19",
"Creuse": "23",
"Dordogne": "24",
"Gironde" :"33",
"Landes": "40",
"Lot-et-Garonne": "47",
"Pyrénées-Atlantiques" :"64",
"Deux-Sèvres": "79",
    "Haute-Vienne": "87",
"Vienne": "86",

}
categories = {"- Ensemble -":"taux_chomage_ensemble","- Ensemble des 15 à 24 ans -":"taux_chomage_15_24","- Ensemble des 25 à 49 ans -":"taux_chomage_25_49","- Ensemble des 50 ans ou plus -":"taux_chomage_50_+","- Femmes -":"taux_chomage_femme","- Hommes -":"taux_chomage_homme"}
print('|'.join(dicT_dep))

Charente-Maritime|Charente|Corrèze|Creuse|Dordogne|Gironde|Landes|Lot-et-Garonne|Pyrénées-Atlantiques|Deux-Sèvres|Haute-Vienne|Vienne

In [3]:
df = pd.read_excel("taux-chommage.xlsx")

/Users/alisaleh/anaconda3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
df

,Libellé,idBank,Dernière mise à jour,Période,1982,1983,1984,1985,1986,1987,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Taux de chômage au sens du BIT (moyenne annuel...,1787752,30/08/2016 00:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),13.5,13.6,(O),(O),(O),(O),(O),(O),(O)
1,Taux de chômage au sens du BIT (moyenne annuel...,1787747,30/08/2016 00:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),24.1,22.9,(O),(O),(O),(O),(O),(O),(O)
2,Taux de chômage au sens du BIT (moyenne annuel...,1787751,30/08/2016 00:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),24.4,23.1,(O),(O),(O),(O),(O),(O),(O)
3,Taux de chômage au sens du BIT (moyenne annuel...,1787748,30/08/2016 00:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),23.3,22.0,(O),(O),(O),(O),(O),(O),(O)
4,Taux de chômage au sens du BIT (moyenne annuel...,1787749,30/08/2016 00:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),24.8,23.9,(O),(O),(O),(O),(O),(O),(O)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Taux de chômage au sens du BIT (moyenne annuel...,1787724,25/05/2023 12:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),21.8,21.3,22.1,21.3,20.9,19,16.1,17,17.4
698,Taux de chômage au sens du BIT (moyenne annuel...,1787730,25/05/2023 12:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),19.0,19.3,17.6,15.3,17.8,17.3,12.4,12.1,12.2
699,Taux de chômage au sens du BIT (moyenne annuel...,1787736,25/05/2023 12:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),16.7,17.9,21.1,19.7,17.4,18.8,12.7,13.3,11.6
700,Taux de chômage au sens du BIT (moyenne annuel...,1787742,25/05/2023 12:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),26.8,22.4,22,22.4,23.4,20.9,18.1,18.9,19.8
701,Taux de chômage au sens du BIT (moyenne annuel...,1787718,25/05/2023 12:00,NaN,(O),(O),(O),(O),(O),(O),...,(O),10.5,10.8,10.3,9.5,9,8.5,8.1,8,7.5

In [5]:
df=df[df["Libellé"].str.contains('|'.join(dicT_dep))]
df.drop(["idBank","Dernière mise à jour","Période"],axis=1, inplace=True)
df

/var/folders/6l/7z68vf196xjd9mbcdm1sw6pm0000gn/T/ipykernel_7744/1343550197.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["idBank","Dernière mise à jour","Période"],axis=1, inplace=True)

,Libellé,1982,1983,1984,1985,1986,1987,1988,1989,1990,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
21,Taux de chômage localisés (moyenne annuelle) -...,7.1,7.5,8.4,9.1,9.3,9.5,9,8.5,8.2,...,10.3,10.1,10.1,9.7,8.9,8.6,8.1,7.8,7.4,6.9
22,Taux de chômage localisés (moyenne annuelle) -...,9.2,9.6,10.8,11.2,11.4,11.3,11,10.3,10.1,...,10.5,10.4,10.7,10.3,9.5,9,8.5,8.2,7.8,6.9
24,Taux de chômage localisés (moyenne annuelle) -...,5.1,5.5,6.9,7.9,8,7.9,7.4,6.9,7.1,...,8.1,8.0,8.2,8.2,7.4,7.2,6.7,6.5,6.4,6.1
27,Taux de chômage localisés (moyenne annuelle) -...,5.7,6.3,8.2,8.3,8.4,8.7,8.6,8.2,7.7,...,9.8,9.4,9.5,9.1,8.5,8.5,7.9,7.1,7,7
28,Taux de chômage localisés (moyenne annuelle) -...,5.9,6.8,8.1,8.9,9,9,8.6,8.2,7.9,...,10.6,10.6,10.7,10.3,9.6,9.1,8.5,8,7.6,7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.9,10.0,10.5,10.2,9.1,8.7,8.4,7.8,7.7,7.4
625,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.3,8.5,8.7,8.3,7.7,7.3,6.9,6.6,6.3,5.8
640,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,7.8,8.0,8.5,8.1,7.3,6.8,6.3,6.1,5.8,5.5
647,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.5,8.8,9.2,8.8,8,7.6,7.2,6.8,6.6,6.2
648,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,10.2,10.2,10.6,10,9,8.4,7.9,7.5,7.2,6.9

In [6]:
def get_dep(row):
    for dep in dicT_dep:
        if dep  in  row:
            return dicT_dep[dep]

In [7]:
df["Code du département"] = df["Libellé"].apply(get_dep)
df

/var/folders/6l/7z68vf196xjd9mbcdm1sw6pm0000gn/T/ipykernel_7744/388585703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Code du département"] = df["Libellé"].apply(get_dep)

,Libellé,1982,1983,1984,1985,1986,1987,1988,1989,1990,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Code du département
21,Taux de chômage localisés (moyenne annuelle) -...,7.1,7.5,8.4,9.1,9.3,9.5,9,8.5,8.2,...,10.1,10.1,9.7,8.9,8.6,8.1,7.8,7.4,6.9,16
22,Taux de chômage localisés (moyenne annuelle) -...,9.2,9.6,10.8,11.2,11.4,11.3,11,10.3,10.1,...,10.4,10.7,10.3,9.5,9,8.5,8.2,7.8,6.9,17
24,Taux de chômage localisés (moyenne annuelle) -...,5.1,5.5,6.9,7.9,8,7.9,7.4,6.9,7.1,...,8.0,8.2,8.2,7.4,7.2,6.7,6.5,6.4,6.1,19
27,Taux de chômage localisés (moyenne annuelle) -...,5.7,6.3,8.2,8.3,8.4,8.7,8.6,8.2,7.7,...,9.4,9.5,9.1,8.5,8.5,7.9,7.1,7,7,23
28,Taux de chômage localisés (moyenne annuelle) -...,5.9,6.8,8.1,8.9,9,9,8.6,8.2,7.9,...,10.6,10.7,10.3,9.6,9.1,8.5,8,7.6,7.2,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,10.0,10.5,10.2,9.1,8.7,8.4,7.8,7.7,7.4,47
625,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.5,8.7,8.3,7.7,7.3,6.9,6.6,6.3,5.8,64
640,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.0,8.5,8.1,7.3,6.8,6.3,6.1,5.8,5.5,79
647,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.8,9.2,8.8,8,7.6,7.2,6.8,6.6,6.2,86
648,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,10.2,10.6,10,9,8.4,7.9,7.5,7.2,6.9,87

In [8]:
df[df["Libellé"].str.contains("Ensemble")]

,Libellé,1982,1983,1984,1985,1986,1987,1988,1989,1990,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Code du département
21,Taux de chômage localisés (moyenne annuelle) -...,7.1,7.5,8.4,9.1,9.3,9.5,9,8.5,8.2,...,10.1,10.1,9.7,8.9,8.6,8.1,7.8,7.4,6.9,16
22,Taux de chômage localisés (moyenne annuelle) -...,9.2,9.6,10.8,11.2,11.4,11.3,11,10.3,10.1,...,10.4,10.7,10.3,9.5,9,8.5,8.2,7.8,6.9,17
24,Taux de chômage localisés (moyenne annuelle) -...,5.1,5.5,6.9,7.9,8,7.9,7.4,6.9,7.1,...,8.0,8.2,8.2,7.4,7.2,6.7,6.5,6.4,6.1,19
27,Taux de chômage localisés (moyenne annuelle) -...,5.7,6.3,8.2,8.3,8.4,8.7,8.6,8.2,7.7,...,9.4,9.5,9.1,8.5,8.5,7.9,7.1,7,7,23
28,Taux de chômage localisés (moyenne annuelle) -...,5.9,6.8,8.1,8.9,9,9,8.6,8.2,7.9,...,10.6,10.7,10.3,9.6,9.1,8.5,8,7.6,7.2,24
39,Taux de chômage localisés (moyenne annuelle) -...,8.6,8.6,9.8,10,10,10.1,9.8,9.2,8.6,...,10.1,10.3,10,9.4,8.8,8.1,7.7,7.3,6.5,33
46,Taux de chômage localisés (moyenne annuelle) -...,5.6,5.9,6.8,7.1,7.2,7.4,7.2,6.7,6.1,...,9.4,9.6,9.4,9,8.5,8,7.7,7.5,6.9,40
53,Taux de chômage localisés (moyenne annuelle) -...,7.3,7.6,8.6,9.2,9,9.1,8.7,8.6,8.3,...,10.0,10.3,10.2,9.3,8.9,8.6,7.9,7.8,7.4,47
70,Taux de chômage localisés (moyenne annuelle) -...,7.6,7.9,9.6,9.8,9.9,9.9,9.5,8.7,8,...,8.6,8.6,8.3,7.8,7.5,7,6.7,6.4,5.7,64
85,Taux de chômage localisés (moyenne annuelle) -...,7,7.1,8.4,9.1,9,8.9,8.7,8.3,7.8,...,7.7,8.0,7.9,7.2,6.7,6.2,6,5.6,5.3,79
92,Taux de chômage localisés (moyenne annuelle) -...,7.6,8.1,9.7,9.9,9.6,9.4,8.8,8.2,7.6,...,8.4,8.5,8.4,7.6,7.4,6.9,6.6,6.4,5.9,86
93,Taux de chômage localisés (moyenne annuelle) -...,5,5.4,6.6,7.5,7.2,7.2,6.6,6.3,6.1,...,9.6,9.8,9.5,8.7,8.1,7.7,7.3,6.9,6.5,87
132,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,27.7,28.4,28.1,24.3,22.9,22.4,23.5,20.3,18.7,16
133,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,26.9,28.2,27.4,24.6,23.5,22.5,24,20.6,17.8,17
135,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,20.4,21.2,21.9,19.4,19.9,19.3,19.7,17.1,15.5,19
138,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,28.2,28.5,27.8,24,23.9,23.6,23,19.8,19,23
139,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,29.9,30.5,29.9,26.6,24.2,24,24.3,20.9,19.7,24
150,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,25.7,26.6,26.5,23.7,21.8,20.3,21.1,18,15.7,33
157,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,26.7,28.0,28.1,24.5,22.4,22.5,22.9,19.9,17.8,40
164,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,26.6,27.8,28.2,24.8,23.8,22.7,21.9,19.6,18.4,47
181,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,24.1,24.7,24,20.9,19.8,19.5,19.2,16.2,14.1,64
196,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,23.8,24.4,24.6,21.4,19.6,18,18.5,15.6,14.1,79
203,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,23.9,24.5,24.7,22,20.5,18.6,18.9,16.6,14.9,86
204,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,26.4,27.2,27.2,24.4,22.7,21.2,21.1,17.7,16.7,87
243,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.4,9.3,8.8,8,7.7,7.4,7.2,6.8,6.3,16
244,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.4,9.6,9.2,8.4,8,7.5,7.3,6.8,6.1,17
246,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,7.3,7.4,7.3,6.6,6.4,6.1,5.9,5.8,5.6,19
249,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.5,8.5,8.1,7.5,7.5,7,6.5,6.5,6.7,23
250,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.9,9.9,9.5,8.7,8.3,7.8,7.5,7.1,6.8,24
261,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.4,9.5,9.1,8.7,8.1,7.3,6.9,6.5,5.8,33
268,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.5,8.6,8.5,8.1,7.6,7.1,7,6.7,6.2,40
275,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.4,9.6,9.4,8.4,8.1,7.7,7.3,7.3,6.9,47
292,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,8.0,8.0,7.7,7.2,6.9,6.3,6.2,5.8,5.3,64
307,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.7,6.9,6.8,6.2,5.8,5.3,5.2,4.9,4.7,79
314,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,7.6,7.7,7.5,6.8,6.5,6,5.8,5.6,5.2,86
315,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,9.0,9.1,8.7,7.8,7.4,6.8,6.5,6.3,5.9,87
354,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.3,6.3,6.1,6.1,5.9,5.5,4.8,5,4.5,16
355,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,7.1,7.3,7,6.9,6.7,6.3,5.5,5.6,5,17
357,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,5.4,5.6,5.6,5.4,5.1,4.7,4.2,4.5,4.2,19
360,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.7,6.8,6.5,6.4,6.2,5.6,4.6,4.8,4.6,23
361,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,7.0,7.1,6.9,6.8,6.5,6,5.2,5.2,4.8,24
372,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.3,6.4,6.3,6.1,5.7,5.7,5,5.2,4.6,33
379,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.5,6.5,6.4,6.5,6.2,5.8,5.2,5.4,4.9,40
386,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,6.6,6.8,6.7,6.4,6.3,6.1,5.2,5.4,4.9,47
403,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,5.6,5.6,5.6,5.5,5.2,5,4.5,4.6,4.1,64
418,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,5.1,5.2,5.1,4.9,4.6,4.3,3.7,3.8,3.4,79
425,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,5.0,5.0,4.9,4.8,4.6,4.4,3.8,3.9,3.6,86
426,Taux de chômage localisés (moyenne annuelle) -...,(O),(O),(O),(O),(O),(O),(O),(O),(O),...,5.9,6.0,5.8,5.5,5.1,5,4.4,4.6,4.1,87

In [9]:
df_cat = []
for cat in categories:
    print(cat)
    df_ens = df[df["Libellé"].str.contains(cat)]
    
    df_ens=df_ens.drop(["Libellé"],axis=1)
    df_ens=df_ens.melt(['Code du département'], var_name='Année',value_name=categories[cat])
    print(len(df_ens)," pour la categorie ",cat)
    df_cat.append(df_ens)

- Ensemble -
492  pour la categorie  - Ensemble -
- Ensemble des 15 à 24 ans -
492  pour la categorie  - Ensemble des 15 à 24 ans -
- Ensemble des 25 à 49 ans -
492  pour la categorie  - Ensemble des 25 à 49 ans -
- Ensemble des 50 ans ou plus -
492  pour la categorie  - Ensemble des 50 ans ou plus -
- Femmes -
492  pour la categorie  - Femmes -
- Hommes -
492  pour la categorie  - Hommes -

In [10]:

df_cat[3]

    Code du département Année taux_chomage_50_+
0                    16  1982               (O)
1                    17  1982               (O)
2                    19  1982               (O)
3                    23  1982               (O)
4                    24  1982               (O)
..                  ...   ...               ...
487                  47  2022               4.9
488                  64  2022               4.1
489                  79  2022               3.4
490                  86  2022               3.6
491                  87  2022               4.1

[492 rows x 3 columns]

In [11]:

display(df_cat[5][(df_cat[5]["Code du département"]=="86")])

    Code du département Année taux_chomage_homme
10                   86  1982                (O)
22                   86  1983                (O)
34                   86  1984                (O)
46                   86  1985                (O)
58                   86  1986                (O)
70                   86  1987                (O)
82                   86  1988                (O)
94                   86  1989                (O)
106                  86  1990                (O)
118                  86  1991                (O)
130                  86  1992                (O)
142                  86  1993                (O)
154                  86  1994                (O)
166                  86  1995                (O)
178                  86  1996                7.3
190                  86  1997                7.8
202                  86  1998                7.4
214                  86  1999                7.3
226                  86  2000                5.9
238                  86  2001                5.3
250                  86  2002                5.6
262                  86  2003                6.1
274                  86  2004                6.5
286                  86  2005                6.7
298                  86  2006                6.9
310                  86  2007                6.3
322                  86  2008                  6
334                  86  2009                8.1
346                  86  2010                7.9
358                  86  2011                7.7
370                  86  2012                8.3
382                  86  2013                8.5
394                  86  2014                8.8
406                  86  2015                9.2
418                  86  2016                8.8
430                  86  2017                  8
442                  86  2018                7.6
454                  86  2019                7.2
466                  86  2020                6.8
478                  86  2021                6.6
490                  86  2022                6.2

In [12]:
df_merged = functools.reduce(lambda  left,right: pd.merge(left,right,on=['Code du département',"Année"],
                                            how='outer'), df_cat)
df_merged

,Code du département,Année,taux_chomage_ensemble,taux_chomage_15_24,taux_chomage_25_49,taux_chomage_50_+,taux_chomage_femme,taux_chomage_homme
0,16,1982,7.1,(O),(O),(O),(O),(O)
1,17,1982,9.2,(O),(O),(O),(O),(O)
2,19,1982,5.1,(O),(O),(O),(O),(O)
3,23,1982,5.7,(O),(O),(O),(O),(O)
4,24,1982,5.9,(O),(O),(O),(O),(O)
...,...,...,...,...,...,...,...,...
487,47,2022,7.4,18.4,6.9,4.9,7.4,7.4
488,64,2022,5.7,14.1,5.3,4.1,5.7,5.8
489,79,2022,5.3,14.1,4.7,3.4,5,5.5
490,86,2022,5.9,14.9,5.2,3.6,5.6,6.2
491,87,2022,6.5,16.7,5.9,4.1,6.1,6.9

In [14]:
df_merged.to_csv("taux_chomage.csv")